language: node_js
node_js: 8

sudo: required

cache: yarn

script:
  - node index.js

# greenkeeper-lockfile
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
