name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Build
        run: yarn run build

  lint:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint

  run:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true
      - name: Build
        run: yarn run build
      - name: Install browser depenencies
        run: yarn run playwright install-deps ${{ matrix.browser }}
      - name: Install browser
        run: yarn run playwright install ${{ matrix.browser }}
      - name: Run (retry once)
        run: yarn start --browser ${{ matrix.browser }} || yarn start --browser ${{ matrix.browser }}

  build-and-push-docker:
    needs: [build, lint, run]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and Push)
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/ciffelia/fast-speed-test:latest
          cache-from: type=registry,ref=ghcr.io/ciffelia/fast-speed-test:latest
          cache-to: type=inline
          push: ${{ github.ref == 'refs/heads/master' }}
