name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build

  lint:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build
      - run: yarn run lint

  run:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]
        browser: [chromium, firefox, webkit]
        exclude:
          - os: ubuntu-20.04
            browser: webkit

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - run: yarn install --immutable
      - run: yarn run build
      # Retry once
      - run: yarn start --browser ${{ matrix.browser }} || yarn start --browser ${{ matrix.browser }}

  build-and-push-docker:
    needs: [build, lint, run]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/ciffelia/fast-speed-test:latest
          load: true

      - name: Run
        run: docker run --rm ghcr.io/ciffelia/fast-speed-test:latest

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/ciffelia/fast-speed-test:latest
          push: true
